apiVersion: v2
name: home-k8s
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: common
    version: 0.4.0
    repository: "https://jfms7s.github.io/helm-charts"
    alias: bazaar
  - name: common
    version: 0.4.0
    repository: "https://jfms7s.github.io/helm-charts"
    alias: overseerr
  - name: common
    version: 0.4.0
    repository: "https://jfms7s.github.io/helm-charts"
    alias: prowlarr
  - name: common
    version: 0.4.0
    repository: "https://jfms7s.github.io/helm-charts"
    alias: radarr
  - name: common
    version: 0.4.0
    repository: "https://jfms7s.github.io/helm-charts"
    alias: sonarr
  - name: common
    version: 0.4.0
    repository: "https://jfms7s.github.io/helm-charts"
    alias: transmission
  - name: common
    version: 0.4.0
    repository: "https://jfms7s.github.io/helm-charts"
    alias: tautulli
  - name: common
    version: 0.4.0
    repository: "https://jfms7s.github.io/helm-charts"
    alias: flood

