$refs:
  nfs-server: &nfs-server 192.168.0.4
  dockerImages:
    ## https://hub.docker.com/r/linuxserver/bazarr/tags
    bazarr: &bazarr "1.0.2"
    ## https://hub.docker.com/r/linuxserver/overseerr/tags
    overseerr: &overseerr "1.28.0"
    ## https://hub.docker.com/r/linuxserver/prowlarr/tags
    prowlarr: &prowlarr "0.2.0-nightly"
    ## https://hub.docker.com/r/linuxserver/radarr/tags
    radarr: &radarr "4.0.4"
    sonarr: &sonarr "3.0.6"
    transmission: &transmission "3.00-r5-ls112"

bazaar:
  deploy:
    containerPorts:
      http: 6767
    image:
      repository: "linuxserver/bazarr"
      tag: *bazarr
      pullPolicy: IfNotPresent
    extraVolumes: 
      - name: config-volume
        nfs: 
          server: *nfs-server
          path: /volumeUSB1/usbshare/k8s/volumes/bazarr-config
      - name: downloads-volume
        nfs: 
          server: *nfs-server
          path: /volumeUSB1/usbshare
      - name: archive-volume
        nfs: 
          server: *nfs-server
          path: /volume1/media
    extraVolumeMounts: 
      - mountPath: /config
        name: config-volume
      - mountPath: /mnt/archive
        name: archive-volume
      - mountPath: /mnt/downloads 
        name: downloads-volume
  ingress:
    enabled: false
    hostname: "bazarr.k3s.home"
    path: /

overseerr:
  deploy:
    containerPorts:
      http: 5055
    image:
      repository: "lscr.io/linuxserver/overseerr"
      tag: *overseerr
      pullPolicy: IfNotPresent
    extraVolumes: 
      - name: config-volume
        nfs: 
          server: *nfs-server
          path: /volumeUSB1/usbshare/k8s/volumes/overseerr-config
      - name: downloads-volume
        nfs: 
          server: *nfs-server
          path: /volumeUSB1/usbshare
      - name: archive-volume
        nfs: 
          server: *nfs-server
          path: /volume1/media
    extraVolumeMounts: 
      - mountPath: /config
        name: config-volume
      - mountPath: /mnt/archive
        name: archive-volume
      - mountPath: /mnt/downloads 
        name: downloads-volume
  ingress:
    enabled: false
    hostname: "overseerr.k3s.home"
    path: /

prowlarr:
  deploy:
    containerPorts:
      http: 9696
    image:
      repository: "linuxserver/prowlarr"
      tag: *prowlarr
      pullPolicy: IfNotPresent
    extraVolumes: 
      - name: config-volume
        nfs: 
          server: *nfs-server
          path: /volumeUSB1/usbshare/k8s/volumes/prowlarr-config
      - name: downloads-volume
        nfs: 
          server: *nfs-server
          path: /volumeUSB1/usbshare
      - name: archive-volume
        nfs: 
          server: *nfs-server
          path: /volume1/media
    extraVolumeMounts: 
      - mountPath: /config
        name: config-volume
      - mountPath: /mnt/archive
        name: archive-volume
      - mountPath: /mnt/downloads 
        name: downloads-volume
  ingress:
    enabled: false
    hostname: "prowlarr.k3s.home"
    path: /

radarr:
  deploy:
    containerPorts:
      http: 7878
    image:
      repository: "linuxserver/radarr"
      tag: *radarr
      pullPolicy: IfNotPresent
    extraVolumes: 
      - name: config-volume
        nfs: 
          server: *nfs-server
          path: /volumeUSB1/usbshare/k8s/volumes/radarr-config
      - name: downloads-volume
        nfs: 
          server: *nfs-server
          path: /volumeUSB1/usbshare
      - name: archive-volume
        nfs: 
          server: *nfs-server
          path: /volume1/media
    extraVolumeMounts: 
      - mountPath: /config
        name: config-volume
      - mountPath: /mnt/archive
        name: archive-volume
      - mountPath: /mnt/downloads 
        name: downloads-volume
  ingress:
    enabled: false
    hostname: "radarr.k3s.home"
    path: /

sonarr:
  deploy:
    containerPorts:
      http: 8989
    image:
      repository: "linuxserver/sonarr"
      tag: *sonarr
      pullPolicy: IfNotPresent
    extraVolumes: 
      - name: config-volume
        nfs: 
          server: *nfs-server
          path: /volumeUSB1/usbshare/k8s/volumes/sonarr-config
      - name: downloads-volume
        nfs: 
          server: *nfs-server
          path: /volumeUSB1/usbshare
      - name: archive-volume
        nfs: 
          server: *nfs-server
          path: /volume1/media
    extraVolumeMounts: 
      - mountPath: /config
        name: config-volume
      - mountPath: /mnt/archive
        name: archive-volume
      - mountPath: /mnt/downloads 
        name: downloads-volume
  ingress:
    enabled: false
    hostname: "sonarr.k3s.home"
    path: /

transmission:
  deploy:
    env:
      - name: TRANSMISSION_WEB_HOME
        value: "/flood-for-transmission/"
    containerPorts:
      http: 9091
      bit-torrent: 51413
      bit-torrent-udp:
        port: 51413
        protocol: UDP
    image:
      repository: "linuxserver/transmission"
      tag: *transmission
      pullPolicy: IfNotPresent
    extraVolumes: 
      - name: config-volume
        nfs: 
          server: *nfs-server
          path: /volumeUSB1/usbshare/k8s/volumes/transmission-config
      - name: downloads-volume
        nfs: 
          server: *nfs-server
          path: /volumeUSB1/usbshare
      - name: archive-volume
        nfs: 
          server: *nfs-server
          path: /volume1/media
    extraVolumeMounts: 
      - mountPath: /config
        name: config-volume
      - mountPath: /mnt/archive
        name: archive-volume
      - mountPath: /mnt/downloads 
        name: downloads-volume
  ingress:
    enabled: false
    hostname: "transmission.k3s.home"
    path: /
