bazaar:
  deploy:
    containerPorts:
      http: 6767
    image:
      repository: "linuxserver/bazarr"
      tag: "1.0.1"
      pullPolicy: IfNotPresent
    extraVolumes: 
      - name: config-volume
        nfs: 
          server: 192.168.0.4
          path: /volumeUSB1/usbshare/k8s/volumes/bazarr-config
      - name: downloads-volume
        nfs: 
          server: 192.168.0.4
          path: /volumeUSB1/usbshare
      - name: archive-volume
        nfs: 
          server: 192.168.0.4
          path: /volume1/media
    extraVolumeMounts: 
      - mountPath: /config
        name: config-volume
      - mountPath: /mnt/archive
        name: archive-volume
      - mountPath: /mnt/downloads 
        name: downloads-volume
  ingress:
    enabled: false
    hostname: "bazarr.k3s.home"
    path: /

overseerr:
  deploy:
    containerPorts:
      http: 5055
    image:
      repository: "lscr.io/linuxserver/overseerr"
      tag: "1.27.0"
      pullPolicy: IfNotPresent
    extraVolumes: 
      - name: config-volume
        nfs: 
          server: 192.168.0.4
          path: /volumeUSB1/usbshare/k8s/volumes/overseerr-config
      - name: downloads-volume
        nfs: 
          server: 192.168.0.4
          path: /volumeUSB1/usbshare
      - name: archive-volume
        nfs: 
          server: 192.168.0.4
          path: /volume1/media
    extraVolumeMounts: 
      - mountPath: /config
        name: config-volume
      - mountPath: /mnt/archive
        name: archive-volume
      - mountPath: /mnt/downloads 
        name: downloads-volume
  ingress:
    enabled: false
    hostname: "overseerr.k3s.home"
    path: /

prowlarr:
  deploy:
    containerPorts:
      http: 9696
    image:
      repository: "linuxserver/prowlarr"
      tag: "1.8.1259"
      pullPolicy: IfNotPresent
    extraVolumes: 
      - name: config-volume
        nfs: 
          server: 192.168.0.4
          path: /volumeUSB1/usbshare/k8s/volumes/prowlarr-config
      - name: downloads-volume
        nfs: 
          server: 192.168.0.4
          path: /volumeUSB1/usbshare
      - name: archive-volume
        nfs: 
          server: 192.168.0.4
          path: /volume1/media
    extraVolumeMounts: 
      - mountPath: /config
        name: config-volume
      - mountPath: /mnt/archive
        name: archive-volume
      - mountPath: /mnt/downloads 
        name: downloads-volume
  ingress:
    enabled: false
    hostname: "prowlarr.k3s.home"
    path: /

radarr:
  deploy:
    containerPorts:
      http: 7878
    image:
      repository: "linuxserver/radarr"
      tag: "0.0.5473"
      pullPolicy: IfNotPresent
    extraVolumes: 
      - name: config-volume
        nfs: 
          server: 192.168.0.4
          path: /volumeUSB1/usbshare/k8s/volumes/radarr-config
      - name: downloads-volume
        nfs: 
          server: 192.168.0.4
          path: /volumeUSB1/usbshare
      - name: archive-volume
        nfs: 
          server: 192.168.0.4
          path: /volume1/media
    extraVolumeMounts: 
      - mountPath: /config
        name: config-volume
      - mountPath: /mnt/archive
        name: archive-volume
      - mountPath: /mnt/downloads 
        name: downloads-volume
  ingress:
    enabled: false
    hostname: "radarr.k3s.home"
    path: /

sonarr:
  deploy:
    containerPorts:
      http: 8989
    image:
      repository: "linuxserver/sonarr"
      tag: "3.0.6"
      pullPolicy: IfNotPresent
    extraVolumes: 
      - name: config-volume
        nfs: 
          server: 192.168.0.4
          path: /volumeUSB1/usbshare/k8s/volumes/sonarr-config
      - name: downloads-volume
        nfs: 
          server: 192.168.0.4
          path: /volumeUSB1/usbshare
      - name: archive-volume
        nfs: 
          server: 192.168.0.4
          path: /volume1/media
    extraVolumeMounts: 
      - mountPath: /config
        name: config-volume
      - mountPath: /mnt/archive
        name: archive-volume
      - mountPath: /mnt/downloads 
        name: downloads-volume
  ingress:
    enabled: false
    hostname: "sonarr.k3s.home"
    path: /

transmission:
  deploy:
    env:
      - name: TRANSMISSION_WEB_HOME
        value: "/flood-for-transmission/"
    containerPorts:
      http: 9091
      bit-torrent: 51413
      bit-torrent-udp:
        port: 51413
        protocol: UDP
    image:
      repository: "linuxserver/transmission"
      tag: "2021.11.18"
      pullPolicy: IfNotPresent
    extraVolumes: 
      - name: config-volume
        nfs: 
          server: 192.168.0.4
          path: /volumeUSB1/usbshare/k8s/volumes/transmission-config
      - name: downloads-volume
        nfs: 
          server: 192.168.0.4
          path: /volumeUSB1/usbshare
      - name: archive-volume
        nfs: 
          server: 192.168.0.4
          path: /volume1/media
    extraVolumeMounts: 
      - mountPath: /config
        name: config-volume
      - mountPath: /mnt/archive
        name: archive-volume
      - mountPath: /mnt/downloads 
        name: downloads-volume
  ingress:
    enabled: false
    hostname: "transmission.k3s.home"
    path: /
