---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "common.names.fullname" . | quote }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    traefik.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.path | quote }}
spec:

  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: {{ .Values.ingress.pathType | quote }}
            backend: 
              service:
                name: {{ include "common.names.fullname" . | quote }}
                port:
                  number: {{ .Values.deploy.containerPorts.http }}
