---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "common.names.fullname" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "common.names.name" . | quote }}
spec:
    type: ClusterIP
    selector: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "common.names.name" . | quote }}
    ports:
{{- range $k, $v := .Values.deploy.containerPorts }}
  {{- if kindIs "map" $v }}
      - name: {{ $k }}
        port: {{ $v.port }}
        protocol: {{ $v.protocol }}
        targetPort: {{ $v.port }}
  {{- else }}
      - name: {{ $k }}
        port: {{ $v }}
        protocol: TCP
        targetPort: {{ $v }}
  {{- end }}
{{- end }}  
    

    
 